### ISSUE TITLE
eg start failure

### ISSUE THREAD

**Issue by qicz** [envoyproxy/gateway#838]
*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.

*Logs*:
>Include the access logs and the Envoy logs.

```bash
2022-12-29T06:44:29.986Z        INFO    runner/runner.go:44     started {"runner": "infrastructure"}
2022-12-29T06:44:29.987Z        INFO    runner/runner.go:75     started {"runner": "xds-server"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x183d135]

goroutine 925 [running]:
github.com/envoyproxy/gateway/internal/xds/server/runner.(*Runner).subscribeAndTranslate.func1({{0xc00430cb28?, 0xc004a16af0?}, 0xce?, 0xc000ba03a8?})
        /build/internal/xds/server/runner/runner.go:131 +0x55
github.com/envoyproxy/gateway/internal/message.HandleSubscription[...](0xc0002cc7d8?, 0xc000f81f98?)
        /build/internal/message/watchutil.go:28 +0xab
github.com/envoyproxy/gateway/internal/xds/server/runner.(*Runner).subscribeAndTranslate(0xc004c1e0f0, {0x1fd7c50?, 0xc00041c4c0?})
        /build/internal/xds/server/runner/runner.go:121 +0x75
created by github.com/envoyproxy/gateway/internal/xds/server/runner.(*Runner).Start
        /build/internal/xds/server/runner/runner.go:73 +0x16a

```

**Comment by Xunzhuo** [comment]
Fixed by https://github.com/envoyproxy/gateway/pull/745

**Comment by Xunzhuo** [comment]
Related to https://github.com/envoyproxy/gateway/issues/734
